// [Copy the ENTIRE content of the previous "MODIFIED_App.jsx" file here]
import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { initializeApp } from 'firebase/app';
import { getAuth, signInAnonymously, onAuthStateChanged } from 'firebase/auth';
import { getFirestore, collection, query, onSnapshot, setDoc, doc } from 'firebase/firestore';
import { LucideSun, LucideMoon, LucideWand2, LucideLayoutList, LucideDollarSign, LucideUser, LucideCheckCircle, LucideAlertTriangle, LucideLoader, LucideLogOut, LucideFeather, LucideMinimize2, LucideMaximize2, LucideSpellCheck } from 'lucide-react';

// --- CONFIGURATION FROM ENVIRONMENT VARIABLES ---
const APP_ID = import.meta.env.VITE_APP_ID || 'docfusion-prod-default';
const FIREBASE_CONFIG = {
    apiKey: import.meta.env.VITE_FIREBASE_API_KEY,
    authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
    projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID,
    storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
    appId: import.meta.env.VITE_FIREBASE_APP_ID,
};

// The Gemini API key is left blank as per platform instructions.
const API_KEY = ""; 
const AI_API_URL = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-09-2025:generateContent?key=${API_KEY}`;

// --- AI DUMMY DATA FOR OFFLINE FALLBACK (Same as before) ---
const AI_DUMMY_OUTPUT = {
    'Resume / CV': `## ANNA SMITH
**(555) 123-4567 | anna.smith@docfusion.ai | LinkedIn Profile**

### PROFESSIONAL SUMMARY
Highly creative and results-driven Senior Full-Stack Developer with 7 years of experience in the Fintech industry. Proven ability to architect, develop, and launch scalable SaaS products, leading to a 30% increase in user engagement. Seeking to leverage deep technical expertise in a fast-paced environment.

### CORE COMPETENCIES
-   **Technologies:** React, Node.js, TypeScript, PostgreSQL, AWS Lambda, Serverless
-   **Methodologies:** Agile, Scrum, DevOps, Test-Driven Development (TDD)
-   **Soft Skills:** Executive Communication, Team Leadership, Problem Solving

### PROFESSIONAL EXPERIENCE
**Lead Software Architect | FinTrack Solutions | 2021 – Present**
* Designed and implemented the core architecture for a real-time financial tracking application, supporting over 100,000 daily active users.
* Reduced cloud infrastructure costs by 40% through serverless refactoring.

**Software Developer | Innovation Hub | 2017 – 2021**
* Developed microservices for payment processing integration.
* Mentored junior developers on best practices and code reviews.`,
    'Contract': `## CONTRACT AGREEMENT (Consulting Services)

**1. PARTIES**
This Agreement is made on ${new Date().toLocaleDateString()} between:
* **CLIENT:** [Client Name, Address]
* **CONTRACTOR:** [Contractor Name, Address]

**2. SERVICES**
The Contractor agrees to provide web development consulting services, including but not limited to, the scope outlined in Appendix A.

**3. COMPENSATION**
The Client shall compensate the Contractor at a rate of $150 USD per hour, invoiced monthly. Payment is due net 30 days.

**4. TERM**
This Agreement shall commence on the Effective Date and continue until terminated by either party with thirty (30) days written notice.`,
    'default': `## Welcome to your AI Document Draft
This is a standard template generated by DocFusion AI.
The content below is a placeholder. A successful API call would replace this with a fully customized document based on your inputs.

* **Document Type:** Generated based on your specific needs.
* **Tone & Style:** Adjusted to be Formal/Executive, as requested.
* **Next Steps:** Edit the content here, or use the AI Rewrite Tools above.
`
};

const NAV_ITEMS = [
    { id: 'builder', label: 'Document Builder', icon: LucideWand2 },
    { id: 'tools', label: 'AI Tools', icon: LucideLayoutList },
    { id: 'pricing', label: 'Pricing', icon: LucideDollarSign },
];

const DUMMY_TOOL_RESPONSE = {
    proofread: (text) => `**Proofread Result (Simulated):**\n\nOriginal:\n"${text}"\n\nCorrected:\n"The executive summary needs to be clear, concise, and focused on measurable outcomes."`,
    formal: (text) => `**Tone Change to Formal (Simulated):**\n\nOriginal:\n"${text}"\n\nFormalized:\n"We hereby assert that the stipulated requirements necessitate immediate executive review and formal documentation."`,
    shorten: (text) => `**Shortened (Simulated):**\n\nOriginal:\n"${text}"\n\nShortened:\n"Core objectives were met efficiently."`,
    expand: (text) => `**Expanded (Simulated):**\n\nOriginal:\n"${text}"\n\nExpanded:\n"This crucial task was executed flawlessly over a multi-week sprint, incorporating iterative feedback and strict quality assurance protocols, resulting in a superior product launch."`,
};


// --- MAIN APP COMPONENT ---
const App = () => {
    // UI State
    const [currentPage, setCurrentPage] = useState('builder');
    const [isDarkMode, setIsDarkMode] = useState(false);
    const [modal, setModal] = useState({ visible: false, title: '', message: '' });
    const [editorContent, setEditorContent] = useState(AI_DUMMY_OUTPUT.default);
    const [isGenerating, setIsGenerating] = useState(false);
    const [generationCount, setGenerationCount] = useState(3); // Free tier limit

    // Firebase / Backend State
    const [app, setApp] = useState(null);
    const [db, setDb] = useState(null);
    const [auth, setAuth] = useState(null);
    const [userId, setUserId] = useState(null);
    const [isAuthReady, setIsAuthReady] = useState(false);
    const [userDocuments, setUserDocuments] = useState([]);

    // --- FIREBASE INITIALIZATION & AUTHENTICATION ---
    useEffect(() => {
        try {
            if (!FIREBASE_CONFIG.apiKey) {
                console.error("Firebase Config Missing: Cannot initialize Firebase.");
                return;
            }

            // 1. Initialize App
            const firebaseApp = initializeApp(FIREBASE_CONFIG);
            const firebaseAuth = getAuth(firebaseApp);
            const firestoreDb = getFirestore(firebaseApp);

            setApp(firebaseApp);
            setAuth(firebaseAuth);
            setDb(firestoreDb);

            // 2. Sign In Anonymously (Standard deployment approach for this app)
            const signInUser = async () => {
                try {
                    await signInAnonymously(firebaseAuth);
                    console.log("Firebase: Signed in anonymously.");
                } catch (error) {
                    console.error("Firebase Auth Error:", error);
                }
            };

            // 3. Auth State Listener
            const unsubscribe = onAuthStateChanged(firebaseAuth, (user) => {
                if (user) {
                    setUserId(user.uid);
                    setCurrentPage('dashboard');
                } else {
                    setUserId(crypto.randomUUID()); 
                }
                setIsAuthReady(true);
            });

            signInUser();
            return () => unsubscribe();

        } catch (e) {
            console.error("Fatal Firebase Initialization Error:", e);
        }
    }, []); // Empty dependency array runs only once

    // --- FIREBASE FIRESTORE DATA LISTENER ---
    useEffect(() => {
        if (!db || !userId || !isAuthReady) return;

        // Path: /artifacts/{APP_ID}/users/{userId}/documents
        const userDocsRef = collection(db, 'artifacts', APP_ID, 'users', userId, 'documents');
        const q = query(userDocsRef);

        const unsubscribe = onSnapshot(q, (snapshot) => {
            const docs = snapshot.docs.map(doc => ({
                id: doc.id,
                ...doc.data()
            }));
            // Sort by createdAt descending (or use client-side sorting)
            docs.sort((a, b) => (b.createdAt || 0) - (a.createdAt || 0));
            setUserDocuments(docs);
            console.log(`Firestore: Loaded ${docs.length} documents for user ${userId}.`);
        }, (error) => {
            console.error("Firestore Snapshot Error:", error);
        });

        return () => unsubscribe();
    }, [db, userId, isAuthReady]); 

    // --- UI UTILITIES ---
    const navigate = useCallback((page) => {
        if (isGenerating) {
            showModal('Hold On', 'The AI is busy! Please wait for the current operation to complete.');
            return;
        }
        setCurrentPage(page);
    }, [isGenerating]);

    const showModal = (title, message) => {
        setModal({ visible: true, title, message });
    };

    const toggleDarkMode = () => {
        setIsDarkMode(prev => !prev);
    };

    // --- BACKEND LOGIC: AI API CALL ---
    const handleAIGenerate = useCallback(async (params) => {
        if (isGenerating || generationCount <= 0) return;

        setIsGenerating(true);
        setEditorContent('Generating content using Gemini AI. Please wait...'); 
        
        const typeKey = params.type.includes('Resume') ? 'Resume / CV' : params.type.includes('Contract') ? 'Contract' : 'default';
        const dummyOutput = AI_DUMMY_OUTPUT[typeKey];

        // --- GEMINI API CALL INTEGRATION ---
        const systemPrompt = `You are DocFusion AI, a world-class document generator. Your task is to generate a professional, highly structured document based on the user's input. Format the response using clean markdown with headers, sub-headers, and bullet points. Do not include any extra conversational text.`;
        const userQuery = `Generate a document of type: ${params.type}, for the role: ${params.role}, in the industry: ${params.industry}, using a ${params.tone} tone. Key details: ${params.details}. The document must be complete and ready for immediate professional use.`;
        
        const payload = {
            contents: [{ parts: [{ text: userQuery }] }],
            systemInstruction: { parts: [{ text: systemPrompt }] },
        };

        try {
            const response = await fetch(AI_API_URL, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(payload)
            });

            if (!response.ok) throw new Error(`API returned status ${response.status}`);
            
            const result = await response.json();
            const generatedText = result.candidates?.[0]?.content?.parts?.[0]?.text || dummyOutput;
            
            setEditorContent(generatedText);
            setGenerationCount(prev => Math.max(0, prev - 1)); 

        } catch (error) {
            console.error("AI API Error (Fallback to Dummy):", error);
            showModal('AI Error', 'Could not reach the Gemini API. Falling back to structured dummy content. Check console for details.');
            setEditorContent(dummyOutput); 
        } finally {
            setIsGenerating(false);
        }
    }, [isGenerating, generationCount]);

    // --- BACKEND LOGIC: AI REWRITE TOOL ---
    const handleAITool = useCallback(async (tool, selectionText) => {
        if (isGenerating || !selectionText) return showModal('Input Required', 'Please select text in the editor to use the AI tool.');

        setIsGenerating(true);
        
        // --- GEMINI API CALL FOR REWRITE ---
        const toolAction = {
            proofread: 'Proofread and correct all grammar and spelling errors.',
            formal: 'Rewrite this text in an extremely formal, executive, and professional tone.',
            shorten: 'Condense this text significantly while preserving the core meaning.',
            expand: 'Expand this text into a detailed paragraph, adding professional context and examples.'
        };

        const systemPrompt = `You are DocFusion AI's rewrite engine. Perform the following action: ${toolAction[tool]} on the user-provided text. Output only the revised text.`;
        const userQuery = `Text to revise: "${selectionText}"`;

        const payload = {
            contents: [{ parts: [{ text: userQuery }] }],
            systemInstruction: { parts: [{ text: systemPrompt }] },
        };

        let revisedText = DUMMY_TOOL_RESPONSE[tool](selectionText); 
        
        try {
            const response = await fetch(AI_API_URL, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(payload)
            });

            if (!response.ok) throw new Error(`API returned status ${response.status}`);
            
            const result = await response.json();
            revisedText = result.candidates?.[0]?.content?.parts?.[0]?.text || revisedText;
            
            const editorDiv = document.getElementById('doc-editor-content');
            const newContent = editorDiv.innerText.replace(selectionText, revisedText);
            setEditorContent(newContent);
            showModal('Tool Success', `${tool} operation completed! Text updated in the editor.`);

        } catch (error) {
            console.error("AI Tool API Error (Fallback to Dummy):", error);
            showModal('AI Tool Error', 'Tool failed. Falling back to simulated result.');
        } finally {
            setIsGenerating(false);
        }
    }, [isGenerating]);


    // --- BACKEND LOGIC: DOCUMENT CRUD (Save) ---
    const saveDocument = async () => {
        if (!db || !userId) {
            return showModal('Access Denied', 'Please log in or wait for the system to initialize.');
        }
        
        const docName = document.getElementById('doc-type')?.value || 'Untitled Document';
        const docRef = doc(collection(db, 'artifacts', APP_ID, 'users', userId, 'documents'));
        
        try {
            await setDoc(docRef, {
                title: docName,
                content: editorContent,
                createdAt: Date.now(),
                lastUpdated: Date.now(),
                type: document.getElementById('doc-type')?.value || 'General',
                userId: userId,
            });
            showModal('Save Success', `Document "${docName}" successfully saved to your cloud history!`);
        } catch (e) {
            console.error("Error saving document:", e);
            showModal('Save Failed', 'Could not save the document. Check your connection and console logs.');
        }
    };
    
    // --- COMPONENT RENDER: UI BLOCKS ---

    const Navbar = () => (
        <nav className="sticky top-0 z-50 bg-white dark:bg-gray-900 border-b border-gray-200 dark:border-gray-700 shadow-md">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div className="flex items-center justify-between h-16">
                    <button onClick={() => navigate('builder')} className="flex-shrink-0 flex items-center space-x-2">
                        <LucideWand2 className="text-indigo-600 dark:text-indigo-400 w-6 h-6" />
                        <span className="text-2xl font-bold tracking-tight text-gray-900 dark:text-white">DocFusion <span className="text-indigo-600 dark:text-indigo-400">AI</span></span>
                    </button>
                    <div className="hidden md:flex items-center space-x-4">
                        {NAV_ITEMS.map(item => (
                            <button key={item.id} onClick={() => navigate(item.id)} className={`px-3 py-2 rounded-md text-sm font-medium transition ${currentPage === item.id ? 'bg-indigo-50 dark:bg-gray-700 text-indigo-700 dark:text-indigo-400' : 'text-gray-700 dark:text-gray-300 hover:text-indigo-700 dark:hover:text-indigo-400'}`}>
                                {item.label}
                            </button>
                        ))}
                    </div>
                    <div className="flex items-center space-x-3">
                        <button onClick={toggleDarkMode} className="p-2 rounded-full hover:bg-gray-100 dark:hover:bg-gray-700 transition">
                            {isDarkMode ? <LucideSun className="text-yellow-500 w-5 h-5" /> : <LucideMoon className="text-indigo-600 w-5 h-5" />}
                        </button>
                        <button onClick={() => navigate('dashboard')} className="bg-indigo-600 hover:bg-indigo-700 text-white font-semibold py-1.5 px-4 rounded-lg shadow-md transition duration-200 text-sm flex items-center">
                            <LucideUser className="w-4 h-4 mr-1" /> Account
                        </button>
                    </div>
                </div>
            </div>
        </nav>
    );

    const BuilderPage = useMemo(() => {
        const handleGenerate = () => {
            const params = {
                type: document.getElementById('doc-type').value,
                role: document.getElementById('doc-role').value,
                industry: document.getElementById('doc-industry').value,
                tone: document.getElementById('doc-tone').value,
                details: document.getElementById('doc-details').value,
            };
            handleAIGenerate(params);
        };

        const handleToolClick = (tool) => {
            const selection = window.getSelection().toString().trim();
            handleAITool(tool, selection);
        };

        const handleExport = (format) => {
            const message = `Simulation: Document content for "${document.getElementById('doc-type').value}" prepared for ${format.toUpperCase()} export. (This requires a backend service like Puppeteer for real PDF/DOCX generation.)`;
            showModal(`Exporting as ${format.toUpperCase()}`, message);
        };

        return (
            <div className="flex flex-col lg:flex-row gap-6 p-4">
                {/* Builder Sidebar (AI Inputs) */}
                <div className="lg:w-1/3 p-6 bg-white dark:bg-gray-800 rounded-xl shadow-lg sticky top-20 h-full">
                    <h3 className="text-xl font-semibold mb-6 border-b pb-3 border-gray-700 dark:border-gray-600">Document Parameters</h3>
                    <div className="space-y-4">
                        {/* Input Fields (Simplified from HTML) */}
                        <InputGroup id="doc-type" label="Document Type" type="select" options={['Resume / CV', 'Cover Letter', 'Contract', 'Legal Agreement', 'Business Proposal']} />
                        <InputGroup id="doc-role" label="Your Role / Title" placeholder="Senior Full-Stack Developer" />
                        <InputGroup id="doc-industry" label="Industry" placeholder="Fintech / SaaS" />
                        <InputGroup id="doc-tone" label="Tone of Voice" type="select" options={['Executive / Professional', 'Formal / Legal', 'Friendly / Casual']} />
                        <InputGroup id="doc-details" label="Key Details / Prompt" type="textarea" placeholder="5 years experience, launched 3 products, skills: React, Node, AWS." />
                    </div>

                    <button
                        onClick={handleGenerate}
                        disabled={isGenerating || generationCount <= 0}
                        className={`w-full mt-6 text-white font-bold py-3 rounded-lg shadow-md transition disabled:opacity-50 ${isGenerating ? 'bg-gray-500' : 'bg-indigo-600 hover:bg-indigo-700'}`}
                    >
                        {isGenerating ? <LucideLoader className="w-5 h-5 animate-spin mx-auto" /> : `Generate Document (${generationCount} left)`}
                    </button>

                    <p className="text-xs text-center text-gray-400 mt-3">
                        {generationCount <= 0 ? (
                            <span>Free Plan Limit Reached. <button onClick={() => navigate('pricing')} className="text-indigo-400 hover:underline">Upgrade to Pro.</button></span>
                        ) : (
                            <span>**POST /v1beta/models/...:generateContent** (Gemini AI Endpoint)</span>
                        )}
                    </p>
                </div>

                {/* Editor Area */}
                <div className="lg:w-2/3">
                    {/* AI Rewrite Toolbar */}
                    <div className="flex flex-wrap gap-2 mb-4 p-4 bg-white dark:bg-gray-800 rounded-xl shadow-lg">
                        <span className="text-sm font-medium mr-2 self-center">AI Tools:</span>
                        <ToolButton icon="SpellCheck" label="Proofread" onClick={() => handleToolClick('proofread')} disabled={isGenerating} />
                        <ToolButton icon="Feather" label="Formal Tone" onClick={() => handleToolClick('formal')} disabled={isGenerating} />
                        <ToolButton icon="Minimize2" label="Shorten" onClick={() => handleToolClick('shorten')} disabled={isGenerating} />
                        <ToolButton icon="Maximize2" label="Expand" onClick={() => handleToolClick('expand')} disabled={isGenerating} />
                    </div>

                    {/* Document Editor */}
                    <div className="p-8 bg-white dark:bg-gray-900 border dark:border-gray-700 rounded-xl shadow-2xl">
                        <div
                            id="doc-editor-content"
                            contentEditable={!isGenerating}
                            spellCheck="true"
                            onInput={(e) => setEditorContent(e.currentTarget.innerText)}
                            dangerouslySetInnerHTML={{ __html: editorContent.replace(/\n/g, '<br/>') }}
                            className={`min-h-[500px] p-2 focus:outline-none text-base transition duration-300 ${isGenerating ? 'text-gray-500 italic' : ''}`}
                        />
                    </div>

                    {/* Export/Save Options */}
                    <div className="mt-6 flex flex-wrap justify-end gap-3 p-4 bg-white dark:bg-gray-800 rounded-xl shadow-lg">
                        <button onClick={saveDocument} className="export-btn bg-green-600 hover:bg-green-700 text-white">
                            <LucideCheckCircle className="w-4 h-4 mr-1" /> Save to Cloud
                        </button>
                        <button onClick={() => handleExport('pdf')} className="export-btn bg-red-600 hover:bg-red-700 text-white">
                            <LucideLayoutList className="w-4 h-4 mr-1" /> Export PDF
                        </button>
                        <button onClick={() => handleExport('docx')} className="export-btn bg-blue-600 hover:bg-blue-700 text-white">
                            <LucideLayoutList className="w-4 h-4 mr-1" /> Export DOCX
                        </button>
                    </div>
                </div>
            </div>
        );
    }, [isGenerating, generationCount, editorContent, handleAIGenerate, handleAITool, navigate, saveDocument]);

    const DashboardPage = useMemo(() => (
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <h2 className="text-3xl font-bold mb-8 text-center">User Dashboard</h2>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                {/* Account Panel */}
                <div className="lg:col-span-1 p-6 bg-white dark:bg-gray-800 rounded-xl shadow-lg">
                    <h3 className="text-xl font-semibold mb-4 border-b pb-3 border-gray-700 dark:border-gray-600">Account Status (App ID: {APP_ID})</h3>
                    <p className="text-sm my-2">User ID: <span className="font-mono text-xs text-indigo-600 dark:text-indigo-400 break-all">{userId || 'Loading...'}</span></p>
                    <p className="text-sm my-2">Plan: <span className="font-bold text-indigo-600">Free</span></p>
                    <p className="text-sm my-2">Generations Left: <span className="font-bold">{generationCount}</span></p>
                    <p className="text-xs text-gray-500 dark:text-gray-400 mt-4">
                        {isAuthReady ? (
                            <span className="text-green-500 flex items-center"><LucideCheckCircle className="w-4 h-4 mr-1"/> Firebase Connected</span>
                        ) : (
                            <span className="text-yellow-500 flex items-center"><LucideLoader className="w-4 h-4 mr-1 animate-spin"/> Authenticating...</span>
                        )}
                    </p>
                    <button onClick={() => { auth.signOut(); navigate('auth'); }} className="mt-6 w-full bg-red-500 hover:bg-red-600 text-white font-bold py-2 rounded-lg transition flex items-center justify-center">
                        <LucideLogOut className="w-4 h-4 mr-2" /> Logout
                    </button>
                </div>

                {/* Document History */}
                <div className="lg:col-span-2 p-6 bg-white dark:bg-gray-800 rounded-xl shadow-lg">
                    <h3 className="text-xl font-semibold mb-4 border-b pb-3 border-gray-700 dark:border-gray-600">Document History ({userDocuments.length} Saved)</h3>
                    <div className="space-y-3 max-h-96 overflow-y-auto">
                        {userDocuments.length === 0 ? (
                            <p className="text-center italic text-gray-500 dark:text-gray-400 py-10">No documents saved yet. Start creating!</p>
                        ) : (
                            userDocuments.map((doc) => (
                                <div key={doc.id} className="flex items-center justify-between p-3 bg-gray-50 dark:bg-gray-700 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-600 transition">
                                    <span className="font-medium truncate">{doc.title}</span>
                                    <div className="flex items-center space-x-3 text-sm">
                                        <span className="text-xs text-gray-500">{new Date(doc.lastUpdated).toLocaleDateString()}</span>
                                        <button onClick={() => { setEditorContent(doc.content); navigate('builder'); }} className="text-indigo-600 hover:text-indigo-400"><LucideWand2 className="w-4 h-4" /></button>
                                        {/* Delete placeholder - Future Implementation */}
                                    </div>
                                </div>
                            ))
                        )}
                    </div>
                </div>
            </div>
        </div>
    ), [userId, isAuthReady, generationCount, userDocuments, navigate, auth]);

    // --- RENDER MAIN LAYOUT ---
    return (
        <div className={isDarkMode ? 'dark' : ''}>
            <div className="bg-gray-50 dark:bg-gray-900 text-gray-800 dark:text-gray-200 min-h-screen transition-colors duration-300">
                <Navbar />

                <main className="py-12">
                    {currentPage === 'builder' && BuilderPage}
                    {currentPage === 'dashboard' && DashboardPage}
                    {currentPage === 'tools' && <h2 className="text-3xl font-bold mb-8 text-center">AI Tools Page (See Builder Toolbar)</h2>}
                    {currentPage === 'pricing' && <h2 className="text-3xl font-bold mb-8 text-center">Pricing Page (Stripe Placeholders)</h2>}
                    {currentPage === 'auth' && <h2 className="text-3xl font-bold mb-8 text-center">Login/Signup Page (Uses Firebase Auth)</h2>}
                </main>

                <Footer />
            </div>

            {/* Custom Modal */}
            {modal.visible && (
                <div className="fixed inset-0 bg-black bg-opacity-70 flex items-center justify-center z-[200] p-4">
                    <div className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow-2xl w-full max-w-sm text-center border-t-4 border-indigo-600">
                        <h3 className="text-xl font-bold mb-4">{modal.title}</h3>
                        <p className="text-sm text-gray-600 dark:text-gray-300 mb-6" dangerouslySetInnerHTML={{ __html: modal.message }} />
                        <button onClick={() => setModal({ visible: false, title: '', message: '' })} className="w-full bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 rounded-lg transition">
                            Got It
                        </button>
                    </div>
                </div>
            )}
        </div>
    );
};

// --- SUB COMPONENTS (Kept the same) ---

const InputGroup = ({ id, label, type = 'text', placeholder, options = [] }) => {
    const isTextarea = type === 'textarea';
    const isSelect = type === 'select';
    
    return (
        <div>
            <label htmlFor={id} className="block text-sm font-medium mb-1">
                {label}
            </label>
            {isSelect ? (
                <select id={id} className="w-full p-2.5 rounded-lg border bg-gray-50 dark:bg-gray-700 border-gray-300 dark:border-gray-600 focus:ring-indigo-500 focus:border-indigo-500 transition text-gray-900 dark:text-gray-200">
                    {options.map((opt) => (
                        <option key={opt}>{opt}</option>
                    ))}
                </select>
            ) : isTextarea ? (
                <textarea
                    id={id}
                    rows="4"
                    placeholder={placeholder}
                    className="w-full p-2.5 rounded-lg border bg-gray-50 dark:bg-gray-700 border-gray-300 dark:border-gray-600 focus:ring-indigo-500 focus:border-indigo-500 transition text-gray-900 dark:text-gray-200"
                ></textarea>
            ) : (
                <input
                    type={type}
                    id={id}
                    placeholder={placeholder}
                    className="w-full p-2.5 rounded-lg border bg-gray-50 dark:bg-gray-700 border-gray-300 dark:border-gray-600 focus:ring-indigo-500 focus:border-indigo-500 transition text-gray-900 dark:text-gray-200"
                />
            )}
        </div>
    );
};

const ToolButton = ({ icon, label, onClick, disabled }) => {
    const IconComponent = { SpellCheck: LucideSpellCheck, Feather: LucideFeather, Minimize2: LucideMinimize2, Maximize2: LucideMaximize2 }[icon];
    return (
        <button
            onClick={onClick}
            disabled={disabled}
            className={`flex items-center space-x-1 px-3 py-1.5 rounded-full text-sm font-medium transition disabled:opacity-50 ${disabled ? 'bg-gray-500 cursor-not-allowed' : 'bg-indigo-100 text-indigo-700 hover:bg-indigo-200 dark:bg-indigo-900 dark:text-indigo-300 dark:hover:bg-indigo-800'}`}
        >
            {IconComponent && <IconComponent className="w-4 h-4" />}
            <span>{label}</span>
        </button>
    );
};

const Footer = () => (
    <footer className="py-8 border-t border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 mt-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center text-sm text-gray-500 dark:text-gray-400">
            <p className="mb-2">&copy; 2024 DocFusion AI. All rights reserved.</p>
            <div className="space-x-4">
                <a href="#" className="hover:text-indigo-600 dark:hover:text-indigo-400 transition">About</a>
                <a href="#" className="hover:text-indigo-600 dark:hover:text-indigo-400 transition">Terms</a>
                <a href="#" className="hover:text-indigo-600 dark:hover:text-indigo-400 transition">Privacy</a>
            </div>
        </div>
    </footer>
);

export default App;
